language: php

php:
  - 7.1.3
  - 7.2
  - 7.3

before_script:
  - cp configuration_sample.php configuration.php
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - composer phpstan

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Installs Sensiolabs security checker to check against unsecure libraries
  - php -r "readfile('http://get.sensiolabs.org/security-checker.phar');" > security-checker
  - chmod +x security-checker
  - ./security-checker security:check
