language: php

php:
  - 7.1.3
  - 7.2
  - 7.3

before_script:
  - cp configuration_sample.php configuration.php
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
