name: PHP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, zip, pdo, PDO

    - name: Install dependencies
      run: composer install --no-interaction

    - name: Copy configuration.php
      run: cp configuration_sample.php configuration.php

    - name: Execute tests
      run: vendor/bin/phpunit
